services:
  postgres:
    image: postgres:17
    container_name: leetcode-postgres
    environment:
      POSTGRES_DB: leetcode
      POSTGRES_USER: leetcode
      POSTGRES_PASSWORD: leetcode
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: leetcode-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"   # AMQP protocol port (used by Spring Boot)
      - "15672:15672" # Management Web UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: