spring.application.name=LeetPain
server.port=9000
spring.datasource.url=jdbc:postgresql://localhost:5432/leetcode
spring.datasource.username=leetcode
spring.datasource.password=leetcode
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG
spring.flyway.enabled=true